package dev.syslabs.sentio.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Entity representing an IoT device (e.g. Raspberry Pi detector).
 * The ID is a unique UUID generated by the device itself on first startup.
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "devices")
public class Device {

    /**
     * Unique hardware ID (UUID) generated by the device.
     * This is NOT generated by the database.
     */
    @Id
    @Column(nullable = false, unique = true, length = 100)
    private String id;

    /**
     * User-friendly name for the device (e.g. "Garden Camera")
     */
    @Column(nullable = false)
    private String name;

    /**
     * Keycloak user UUID who owns this device.
     * Each device can only have ONE owner.
     */
    @Column(name = "owner_id", nullable = false)
    private String ownerId;

    /**
     * Set of active services running on this device (e.g. "animal_detector",
     * "weather_station").
     * Updated via MQTT status messages.
     */
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "device_services", joinColumns = @JoinColumn(name = "device_id"))
    @Column(name = "service_name")
    private Set<String> activeServices = new HashSet<>();

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    /**
     * Last known local IP address of the device.
     * Updated via MQTT status messages.
     */
    @Column(name = "ip_address")
    private String ipAddress;

    /**
     * Geographic latitude coordinate of the device.
     * Can be set manually, via GPS sensor, or from IP geolocation.
     */
    @Column(name = "latitude")
    private Double latitude;

    /**
     * Geographic longitude coordinate of the device.
     * Can be set manually, via GPS sensor, or from IP geolocation.
     */
    @Column(name = "longitude")
    private Double longitude;

    /**
     * Whether this is the user's primary device.
     * The primary device is used as default for forecasts, radar, and sensor
     * display.
     * Only one device per user should be primary.
     */
    @Column(name = "is_primary")
    private Boolean isPrimary = false;

    /**
     * Timestamp when the device was last seen/reported status.
     */
    @Column(name = "last_seen")
    private LocalDateTime lastSeen;

    /**
     * BCrypt-hashed MQTT authentication token.
     * This is the permanent token used after pairing code exchange.
     */
    @Column(name = "mqtt_token_hash")
    private String mqttTokenHash;

    /**
     * Temporary pairing code (format: XXXX-XXXX).
     * Displayed to user in dashboard, entered during device setup.
     * Expires after 15 minutes.
     */
    @Column(name = "pairing_code")
    private String pairingCode;

    /**
     * Expiration time for the pairing code.
     * After this time, the code is invalid and must be regenerated.
     */
    @Column(name = "pairing_code_expires_at")
    private LocalDateTime pairingCodeExpiresAt;

    /**
     * Whether the device is currently streaming video.
     * Updated by the stream auth service when streams start/end.
     */
    @Column(name = "stream_active")
    private Boolean streamActive = false;

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
    }
}
