package org.example.backend.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Entity representing an IoT device (e.g. Raspberry Pi detector).
 * The ID is a unique UUID generated by the device itself on first startup.
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "devices")
public class Device {

    /**
     * Unique hardware ID (UUID) generated by the device.
     * This is NOT generated by the database.
     */
    @Id
    @Column(nullable = false, unique = true, length = 100)
    private String id;

    /**
     * User-friendly name for the device (e.g. "Garden Camera")
     */
    @Column(nullable = false)
    private String name;

    /**
     * Set of Keycloak user IDs/Usernames who own this device.
     * Stored as a collection of strings.
     */
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "device_owners", joinColumns = @JoinColumn(name = "device_id"))
    @Column(name = "user_id")
    private Set<String> owners = new HashSet<>();

    /**
     * Set of active services running on this device (e.g. "animal_detector",
     * "weather_station").
     * Updated via MQTT status messages.
     */
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "device_services", joinColumns = @JoinColumn(name = "device_id"))
    @Column(name = "service_name")
    private Set<String> activeServices = new HashSet<>();

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    /**
     * Last known local IP address of the device.
     * Updated via MQTT status messages.
     */
    @Column(name = "ip_address")
    private String ipAddress;

    /**
     * Timestamp when the device was last seen/reported status.
     */
    @Column(name = "last_seen")
    private LocalDateTime lastSeen;

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
    }
}
