name: Feature Request
description: Suggest an idea for the Sentio Systems project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea with us!
  - type: textarea
    id: problem
    attributes:
      label: The Problem
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the ideal solution or new feature you'd like to see.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
