package org.example.backend.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.example.backend.dto.AuthDTOs;
import org.example.backend.event.DeviceRegisteredEvent;
import org.example.backend.event.DeviceUnregisteredEvent;
import org.example.backend.model.Device;
import org.example.backend.repository.DeviceRepository;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Service
@RequiredArgsConstructor
@Slf4j
public class DeviceService {

    private final DeviceRepository deviceRepository;
    private final AuthService authService;
    private final ApplicationEventPublisher eventPublisher;

    /**
     * Registers a device to the current user.
     * If the device is new (first time seen), it is created.
     * If the device exists, the user is added as an owner.
     * 
     * @param deviceId The UUID generated by the device.
     * @param name     User-friendly name for the device.
     */
    @Transactional
    public Device registerDevice(String deviceId, String name) {
        AuthDTOs.UserInfo currentUser = authService.getCurrentUser();
        String username = currentUser.getUsername(); // keycloak username (or ID) used for ownership

        log.info("Registering device {} for user {}", deviceId, username);

        Optional<Device> existingDeviceOpt = deviceRepository.findById(deviceId);
        Device device;
        boolean isNewRegistration = false;

        if (existingDeviceOpt.isPresent()) {
            device = existingDeviceOpt.get();
            // Check if this is a new owner being added
            isNewRegistration = !device.getOwners().contains(username);
            log.info("Device {} already exists. Adding user {} as owner.", deviceId, username);
        } else {
            device = new Device();
            device.setId(deviceId);
            device.setCreatedAt(LocalDateTime.now());
            isNewRegistration = true;
            log.info("Creating new device entry for {}", deviceId);
        }

        device.setName(name);
        device.getOwners().add(username);
        Device savedDevice = deviceRepository.save(device);

        // Publish event if this is a new registration for this user
        if (isNewRegistration) {
            log.info("Publishing DeviceRegisteredEvent for device {} user {}", deviceId, username);
            eventPublisher.publishEvent(new DeviceRegisteredEvent(this, savedDevice, username));
        }

        return savedDevice;
    }

    /**
     * Unregisters a device for the current user.
     * Removes the user from owners list.
     */
    @Transactional
    public void unregisterDevice(String deviceId) {
        AuthDTOs.UserInfo currentUser = authService.getCurrentUser();
        String username = currentUser.getUsername();

        log.info("Unregistering device {} for user {}", deviceId, username);

        deviceRepository.findById(deviceId).ifPresent(device -> {
            boolean wasOwner = device.getOwners().remove(username);
            deviceRepository.save(device);

            // Publish event if user was actually an owner
            if (wasOwner) {
                log.info("Publishing DeviceUnregisteredEvent for device {} user {}", deviceId, username);
                eventPublisher.publishEvent(new DeviceUnregisteredEvent(this, deviceId, username));
            }
        });
    }

    /**
     * Get all devices owned by the current user.
     */
    public List<Device> getMyDevices() {
        AuthDTOs.UserInfo currentUser = authService.getCurrentUser();
        return deviceRepository.findAllByOwnerId(currentUser.getUsername());
    }

    /**
     * Check if the current user has access to the given device ID.
     */
    public boolean hasAccessToDevice(String deviceId) {
        if (deviceId == null)
            return false;
        AuthDTOs.UserInfo currentUser;
        try {
            currentUser = authService.getCurrentUser();
        } catch (Exception e) {
            // If no user context (e.g. system usage), maybe deny?
            // Or if system admin? For now, strict on user.
            return false;
        }

        return deviceRepository.findById(deviceId)
                .map(device -> device.getOwners().contains(currentUser.getUsername()))
                .orElse(false);
    }

    /**
     * Get list of device IDs owned by current user.
     */
    public List<String> getMyDeviceIds() {
        return getMyDevices().stream().map(Device::getId).toList();
    }

    /**
     * Check if the current user has any registered devices.
     * Used for frontend to determine if weather APIs should be called.
     */
    public boolean hasAnyDevices() {
        return !getMyDevices().isEmpty();
    }
}
