package org.example.backend.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.example.backend.dto.AuthDTOs;
import org.example.backend.event.DeviceRegisteredEvent;
import org.example.backend.event.DeviceUnregisteredEvent;
import org.example.backend.model.Device;
import org.example.backend.repository.DeviceRepository;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Service
@RequiredArgsConstructor
@Slf4j
public class DeviceService {

    private final DeviceRepository deviceRepository;
    private final AuthService authService;
    private final ApplicationEventPublisher eventPublisher;

    /**
     * Registers a device to the current user.
     * If the device is new, it is created with the current user as owner.
     * If the device already exists and belongs to another user, registration fails.
     * 
     * @param deviceId The UUID generated by the device.
     * @param name     User-friendly name for the device.
     */
    @Transactional
    public Device registerDevice(String deviceId, String name) {
        AuthDTOs.UserInfo currentUser = authService.getCurrentUser();
        String userId = currentUser.getId(); // Keycloak user UUID used for ownership

        log.info("Registering device {} for user {}", deviceId, userId);

        Optional<Device> existingDeviceOpt = deviceRepository.findById(deviceId);
        Device device;
        boolean isNewRegistration = false;

        if (existingDeviceOpt.isPresent()) {
            device = existingDeviceOpt.get();
            // Check if this device belongs to another user
            if (!device.getOwnerId().equals(userId)) {
                log.warn("Device {} already belongs to another user", deviceId);
                throw new IllegalStateException("Device already belongs to another user");
            }
            log.info("Device {} already registered to this user, updating name", deviceId);
        } else {
            device = new Device();
            device.setId(deviceId);
            device.setOwnerId(userId);
            device.setCreatedAt(LocalDateTime.now());
            isNewRegistration = true;
            log.info("Creating new device entry for {}", deviceId);
        }

        device.setName(name);
        Device savedDevice = deviceRepository.save(device);

        // Publish event if this is a new registration
        if (isNewRegistration) {
            log.info("Publishing DeviceRegisteredEvent for device {} user {}", deviceId, userId);
            eventPublisher.publishEvent(new DeviceRegisteredEvent(this, savedDevice, userId));
        }

        return savedDevice;
    }

    /**
     * Unregisters a device for the current user.
     * Deletes the device since each device has only one owner.
     */
    @Transactional
    public void unregisterDevice(String deviceId) {
        AuthDTOs.UserInfo currentUser = authService.getCurrentUser();
        String userId = currentUser.getId();

        log.info("Unregistering device {} for user {}", deviceId, userId);

        deviceRepository.findById(deviceId).ifPresent(device -> {
            if (device.getOwnerId().equals(userId)) {
                deviceRepository.delete(device);
                log.info("Publishing DeviceUnregisteredEvent for device {} user {}", deviceId, userId);
                eventPublisher.publishEvent(new DeviceUnregisteredEvent(this, deviceId, userId));
            } else {
                log.warn("User {} attempted to unregister device {} owned by {}", userId, deviceId,
                        device.getOwnerId());
            }
        });
    }

    /**
     * Get all devices owned by the current user.
     */
    public List<Device> getMyDevices() {
        AuthDTOs.UserInfo currentUser = authService.getCurrentUser();
        return deviceRepository.findAllByOwnerId(currentUser.getId());
    }

    /**
     * Check if the current user has access to the given device ID.
     */
    public boolean hasAccessToDevice(String deviceId) {
        if (deviceId == null)
            return false;
        AuthDTOs.UserInfo currentUser;
        try {
            currentUser = authService.getCurrentUser();
        } catch (Exception e) {
            return false;
        }

        return deviceRepository.findById(deviceId)
                .map(device -> device.getOwnerId().equals(currentUser.getId()))
                .orElse(false);
    }

    /**
     * Get list of device IDs owned by current user.
     */
    public List<String> getMyDeviceIds() {
        return getMyDevices().stream().map(Device::getId).toList();
    }

    /**
     * Check if the current user has any registered devices.
     */
    public boolean hasAnyDevices() {
        return !getMyDevices().isEmpty();
    }

    /**
     * Get a device by ID if the current user owns it.
     */
    public Optional<Device> getMyDevice(String deviceId) {
        return deviceRepository.findById(deviceId)
                .filter(device -> {
                    try {
                        AuthDTOs.UserInfo currentUser = authService.getCurrentUser();
                        return device.getOwnerId().equals(currentUser.getId());
                    } catch (Exception e) {
                        return false;
                    }
                });
    }

    /**
     * Get the primary device for the current user.
     * Falls back to first device if no primary is set.
     */
    public Optional<Device> getPrimaryDevice() {
        AuthDTOs.UserInfo currentUser = authService.getCurrentUser();
        String userId = currentUser.getId();

        // First try to find explicitly set primary device
        Optional<Device> primary = deviceRepository.findByOwnerIdAndIsPrimaryTrue(userId);
        if (primary.isPresent()) {
            return primary;
        }

        // Fallback to first device with coordinates
        List<Device> devices = deviceRepository.findAllByOwnerId(userId);
        return devices.stream()
                .filter(d -> d.getLatitude() != null && d.getLongitude() != null)
                .findFirst()
                .or(() -> devices.stream().findFirst());
    }

    /**
     * Set a device as the primary device for the current user.
     * Unsets any existing primary device first.
     */
    @Transactional
    public Device setPrimaryDevice(String deviceId) {
        AuthDTOs.UserInfo currentUser = authService.getCurrentUser();
        String userId = currentUser.getId();

        log.info("Setting device {} as primary for user {}", deviceId, userId);

        // Verify the device belongs to this user
        Device device = deviceRepository.findById(deviceId)
                .filter(d -> d.getOwnerId().equals(userId))
                .orElseThrow(() -> new IllegalArgumentException("Device not found or not owned by user"));

        // Unset any existing primary device
        deviceRepository.findByOwnerIdAndIsPrimaryTrue(userId)
                .ifPresent(existingPrimary -> {
                    existingPrimary.setIsPrimary(false);
                    deviceRepository.save(existingPrimary);
                    log.debug("Unset previous primary device: {}", existingPrimary.getId());
                });

        // Set the new primary device
        device.setIsPrimary(true);
        Device savedDevice = deviceRepository.save(device);

        log.info("Device {} is now primary for user {}", deviceId, userId);
        return savedDevice;
    }

    /**
     * Verifies device belongs to current user and returns it.
     * Throws exception if device not found or not owned by user.
     * 
     * @param deviceId The device UUID to verify
     * @return The verified device
     * @throws IllegalArgumentException if device not found or not owned by user
     */
    public Device getVerifiedDevice(String deviceId) {
        AuthDTOs.UserInfo currentUser = authService.getCurrentUser();
        return deviceRepository.findById(deviceId)
                .filter(d -> d.getOwnerId().equals(currentUser.getId()))
                .orElseThrow(() -> new IllegalArgumentException("Device not found or not owned by user"));
    }
}
