package dev.syslabs.sentio.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import dev.syslabs.sentio.dto.AuthDTOs;
import dev.syslabs.sentio.dto.DeviceRegistrationResponse;
import dev.syslabs.sentio.event.DeviceRegisteredEvent;
import dev.syslabs.sentio.event.DeviceUnregisteredEvent;
import dev.syslabs.sentio.model.Device;
import dev.syslabs.sentio.repository.DeviceRepository;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.security.crypto.bcrypt.BCrypt;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.security.SecureRandom;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Service
@RequiredArgsConstructor
@Slf4j
        /**
         * Service for managing IoT device registration, pairing, and ownership.
         * Handles device CRUD operations, MQTT code generation, and event publishing for device lifecycle changes.
         * Integrates with authentication and repository layers.
         */
public class DeviceService {

    private final DeviceRepository deviceRepository;
    private final AuthService authService;
    private final ApplicationEventPublisher eventPublisher;

    private static final SecureRandom SECURE_RANDOM = new SecureRandom();
    private static final String MQTT_CODE_CHARS = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // No I, O, 0, 1

    @Value("${mqtt.external-url:mqtt://localhost:1883}")
    private String mqttExternalUrl;

    /**
     * Registers a device to the current user.
     * If the device is new, it is created with the current user as owner.
     * If the device already exists and belongs to another user, registration fails.
     * 
     * @param deviceId The UUID generated by the device.
     * @param name     User-friendly name for the device.
     */
    @Transactional
    public Device registerDevice(String deviceId, String name) {
        AuthDTOs.UserInfo currentUser = authService.getCurrentUser();
        String userId = currentUser.getId(); // Keycloak user UUID used for ownership

        log.info("Registering device {} for user {}", deviceId, userId);

        Optional<Device> existingDeviceOpt = deviceRepository.findById(deviceId);
        Device device;
        boolean isNewRegistration = false;

        if (existingDeviceOpt.isPresent()) {
            device = existingDeviceOpt.get();
            // Check if this device belongs to another user
            if (!device.getOwnerId().equals(userId)) {
                log.warn("Device {} already belongs to another user", deviceId);
                throw new IllegalStateException("Device already belongs to another user");
            }
            log.info("Device {} already registered to this user, updating name", deviceId);
        } else {
            device = new Device();
            device.setId(deviceId);
            device.setOwnerId(userId);
            device.setCreatedAt(LocalDateTime.now());
            isNewRegistration = true;
            log.info("Creating new device entry for {}", deviceId);
        }

        device.setName(name);
        Device savedDevice = deviceRepository.save(device);

        // Publish event if this is a new registration
        if (isNewRegistration) {
            log.info("Publishing DeviceRegisteredEvent for device {} user {}", deviceId, userId);
            eventPublisher.publishEvent(new DeviceRegisteredEvent(this, savedDevice, userId));
        }

        return savedDevice;
    }

    /**
     * Registers a new device with expiring pairing code.
     * Used by the frontend - user only provides a name.
     * 
     * @param name User-friendly name for the device
     * @return Registration response with device ID and pairing code (valid 15 min)
     */
    @Transactional
    public DeviceRegistrationResponse registerDeviceWithCredentials(String name) {
        AuthDTOs.UserInfo currentUser = authService.getCurrentUser();
        String userId = currentUser.getId();

        // Generate device ID
        String deviceId = UUID.randomUUID().toString();

        // Generate expiring pairing code (format: XXXX-XXXX)
        String pairingCode = generateMqttCode();
        LocalDateTime expiresAt = LocalDateTime.now().plusMinutes(15);

        log.info("Registering new device {} with 15-min pairing code for user {}", deviceId, userId);

        Device device = new Device();
        device.setId(deviceId);
        device.setName(name);
        device.setOwnerId(userId);
        device.setCreatedAt(LocalDateTime.now());
        device.setPairingCode(pairingCode);
        device.setPairingCodeExpiresAt(expiresAt);
        // mqttTokenHash is null until pairing is completed

        Device savedDevice = deviceRepository.save(device);

        log.info("Publishing DeviceRegisteredEvent for device {} user {}", deviceId, userId);
        eventPublisher.publishEvent(new DeviceRegisteredEvent(this, savedDevice, userId));

        return DeviceRegistrationResponse.builder()
                .deviceId(deviceId)
                .name(name)
                .pairingCode(pairingCode)
                .pairingCodeExpiresAt(expiresAt)
                .mqttUrl(mqttExternalUrl)
                .build();
    }

    /**
     * Regenerate pairing code for an existing device.
     * Used when the original code expires or is lost.
     * 
     * @param deviceId The device ID
     * @return New registration response with fresh pairing code
     */
    @Transactional
    public DeviceRegistrationResponse regeneratePairingCode(String deviceId) {
        AuthDTOs.UserInfo currentUser = authService.getCurrentUser();
        String userId = currentUser.getId();

        Device device = deviceRepository.findById(deviceId)
                .filter(d -> d.getOwnerId().equals(userId))
                .orElseThrow(() -> new IllegalArgumentException("Device not found or not owned by user"));

        // Generate new expiring pairing code
        String pairingCode = generateMqttCode();
        LocalDateTime expiresAt = LocalDateTime.now().plusMinutes(15);

        device.setPairingCode(pairingCode);
        device.setPairingCodeExpiresAt(expiresAt);
        // Clear existing token on regenerate - device needs to re-pair
        device.setMqttTokenHash(null);

        Device savedDevice = deviceRepository.save(device);

        log.info("Regenerated pairing code for device {} (expires {})", deviceId, expiresAt);

        return DeviceRegistrationResponse.builder()
                .deviceId(savedDevice.getId())
                .name(savedDevice.getName())
                .pairingCode(pairingCode)
                .pairingCodeExpiresAt(expiresAt)
                .mqttUrl(mqttExternalUrl)
                .build();
    }

    /**
     * Exchange pairing code for permanent device token.
     * Called by the device during setup.
     * This is a PUBLIC endpoint - no user auth required.
     * 
     * @param deviceId    The device ID
     * @param pairingCode The pairing code from the dashboard
     * @return Permanent device token for MQTT authentication
     */
    @Transactional
    public String exchangePairingCode(String deviceId, String pairingCode) {
        if (deviceId == null || pairingCode == null) {
            throw new IllegalArgumentException("Device ID and pairing code are required");
        }

        Device device = deviceRepository.findById(deviceId)
                .orElseThrow(() -> new IllegalArgumentException("Device not found"));

        // Check pairing code matches
        if (device.getPairingCode() == null || !device.getPairingCode().equals(pairingCode)) {
            throw new IllegalArgumentException("Invalid pairing code");
        }

        // Check if expired
        if (device.getPairingCodeExpiresAt() == null ||
                LocalDateTime.now().isAfter(device.getPairingCodeExpiresAt())) {
            throw new IllegalArgumentException("Pairing code has expired. Generate a new one in the dashboard.");
        }

        // Generate permanent device token
        String deviceToken = UUID.randomUUID().toString().replace("-", "");
        String hashedToken = BCrypt.hashpw(deviceToken, BCrypt.gensalt());

        device.setMqttTokenHash(hashedToken);
        // Clear pairing code after use (one-time use)
        device.setPairingCode(null);
        device.setPairingCodeExpiresAt(null);

        deviceRepository.save(device);

        log.info("Device {} successfully paired. Pairing code exchanged for permanent token.", deviceId);

        return deviceToken;
    }

    /**
     * Generate a human-readable MQTT code (format: XXXX-XXXX).
     */
    private String generateMqttCode() {
        StringBuilder code = new StringBuilder(9);
        for (int i = 0; i < 8; i++) {
            if (i == 4)
                code.append('-');
            code.append(MQTT_CODE_CHARS.charAt(SECURE_RANDOM.nextInt(MQTT_CODE_CHARS.length())));
        }
        return code.toString();
    }

    /**
     * Validate MQTT credentials for device authentication.
     * Called by the MQTT auth plugin.
     * 
     * @param deviceId    The device ID (username)
     * @param deviceToken The permanent device token (password)
     * @return true if valid
     */
    public boolean validateMqttToken(String deviceId, String deviceToken) {
        if (deviceId == null || deviceToken == null) {
            return false;
        }

        return deviceRepository.findById(deviceId)
                .map(device -> {
                    if (device.getMqttTokenHash() == null) {
                        return false;
                    }
                    return BCrypt.checkpw(deviceToken, device.getMqttTokenHash());
                })
                .orElse(false);
    }

    /**
     * Get active services for a device.
     * Used for MQTT ACL checks to determine topic permissions.
     * 
     * @param deviceId The device ID
     * @return Set of active service names, or empty set if device not found
     */
    public java.util.Set<String> getDeviceServices(String deviceId) {
        if (deviceId == null) {
            return java.util.Collections.emptySet();
        }
        return deviceRepository.findById(deviceId)
                .map(Device::getActiveServices)
                .orElse(java.util.Collections.emptySet());
    }

    /**
     * Unregisters a device for the current user.
     * Deletes the device since each device has only one owner.
     */
    @Transactional
    public void unregisterDevice(String deviceId) {
        AuthDTOs.UserInfo currentUser = authService.getCurrentUser();
        String userId = currentUser.getId();

        log.info("Unregistering device {} for user {}", deviceId, userId);

        deviceRepository.findById(deviceId).ifPresent(device -> {
            if (device.getOwnerId().equals(userId)) {
                deviceRepository.delete(device);
                log.info("Publishing DeviceUnregisteredEvent for device {} user {}", deviceId, userId);
                eventPublisher.publishEvent(new DeviceUnregisteredEvent(this, deviceId, userId));
            } else {
                log.warn("User {} attempted to unregister device {} owned by {}", userId, deviceId,
                        device.getOwnerId());
            }
        });
    }

    /**
     * Get all devices owned by the current user.
     */
    public List<Device> getMyDevices() {
        AuthDTOs.UserInfo currentUser = authService.getCurrentUser();
        return deviceRepository.findAllByOwnerId(currentUser.getId());
    }

    /**
     * Check if the current user has access to the given device ID.
     */
    public boolean hasAccessToDevice(String deviceId) {
        if (deviceId == null)
            return false;
        AuthDTOs.UserInfo currentUser;
        try {
            currentUser = authService.getCurrentUser();
        } catch (Exception e) {
            return false;
        }

        return deviceRepository.findById(deviceId)
                .map(device -> device.getOwnerId().equals(currentUser.getId()))
                .orElse(false);
    }

    public List<String> getMyDeviceIds() {
        return getMyDevices().stream().map(Device::getId).toList();
    }

    public boolean hasAnyDevices() {
        return !getMyDevices().isEmpty();
    }

    /**
     * Check if any devices are registered in the system (global check, no user context required).
     * Used by scheduled tasks to decide whether to run weather updates.
     */
    public boolean existsAnyDevice() {
        return deviceRepository.count() > 0;
    }

    /**
     * Get a device by ID if the current user owns it.
     */
    public Optional<Device> getMyDevice(String deviceId) {
        return deviceRepository.findById(deviceId)
                .filter(device -> {
                    try {
                        AuthDTOs.UserInfo currentUser = authService.getCurrentUser();
                        return device.getOwnerId().equals(currentUser.getId());
                    } catch (Exception e) {
                        return false;
                    }
                });
    }

    /**
     * Get the primary device for the current user.
     * Falls back to first device if no primary is set.
     */
    public Optional<Device> getPrimaryDevice() {
        AuthDTOs.UserInfo currentUser = authService.getCurrentUser();
        String userId = currentUser.getId();

        // First try to find explicitly set primary device
        Optional<Device> primary = deviceRepository.findByOwnerIdAndIsPrimaryTrue(userId);
        if (primary.isPresent()) {
            return primary;
        }

        // Fallback to first device with coordinates
        List<Device> devices = deviceRepository.findAllByOwnerId(userId);
        return devices.stream()
                .filter(d -> d.getLatitude() != null && d.getLongitude() != null)
                .findFirst()
                .or(() -> devices.stream().findFirst());
    }

    /**
     * Set a device as the primary device for the current user.
     * Unsets any existing primary device first.
     */
    @Transactional
    public Device setPrimaryDevice(String deviceId) {
        AuthDTOs.UserInfo currentUser = authService.getCurrentUser();
        String userId = currentUser.getId();

        log.info("Setting device {} as primary for user {}", deviceId, userId);

        // Verify the device belongs to this user
        Device device = deviceRepository.findById(deviceId)
                .filter(d -> d.getOwnerId().equals(userId))
                .orElseThrow(() -> new IllegalArgumentException("Device not found or not owned by user"));

        // Unset any existing primary device
        deviceRepository.findByOwnerIdAndIsPrimaryTrue(userId)
                .ifPresent(existingPrimary -> {
                    existingPrimary.setIsPrimary(false);
                    deviceRepository.save(existingPrimary);
                    log.debug("Unset previous primary device: {}", existingPrimary.getId());
                });

        // Set the new primary device
        device.setIsPrimary(true);
        Device savedDevice = deviceRepository.save(device);

        log.info("Device {} is now primary for user {}", deviceId, userId);
        return savedDevice;
    }

    /**
     * Verifies device belongs to current user and returns it.
     * Throws exception if device not found or not owned by user.
     * 
     * @param deviceId The device UUID to verify
     * @return The verified device
     * @throws IllegalArgumentException if device not found or not owned by user
     */
    public Device getVerifiedDevice(String deviceId) {
        AuthDTOs.UserInfo currentUser = authService.getCurrentUser();
        return deviceRepository.findById(deviceId)
                .filter(d -> d.getOwnerId().equals(currentUser.getId()))
                .orElseThrow(() -> new IllegalArgumentException("Device not found or not owned by user"));
    }
}
